version: "2"

run:
  go: "1.24"
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet
    - gocritic
  exclusions:
    generated: lax
    paths:
      - '(^|/)gen(/|$)'
      - '(^|/)vendor(/|$)'

  settings:
    govet:
      disable:
        - copylocks
    staticcheck:
      # default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -QF1008
    errcheck:
      exclude-functions:
        - os.RemoveAll
        - os.Remove
        - (*os.File).Close`
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - fmt.Fprintf
        - fmt.Fprintln
      # Display function signature instead of selector.
      # Default: false
      verbose: true

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - '(^|/)gen(/|$)'
      - '(^|/)vendor(/|$)'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

